params["_caja"];

//Infanteria
_caja addAction ["Loadout <t color='#FF0000'>SARGENTO</t>", {[_this select 1] call ars_inf_sarg;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>CABO</t>", {[_this select 1] call ars_inf_cabo;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>MG</t>", {[_this select 1] call ars_inf_mg;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
//_caja addAction ["Loadout <t color='#FF0000'>AT(Pesado)</t>", {[_this select 1] call ars_inf_atp;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>AT(Ligero)</t>", {[_this select 1] call ars_inf_atl;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>MEDICO</t>", {[_this select 1] call ars_inf_med;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>FUSILERO</t>", {[_this select 1] call ars_inf_fus;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#FF0000'>TD</t>", {[_this select 1] call ars_inf_td;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
//_caja addAction ["Loadout <t color='#FF0000'>TENIENTE</t>", {[_this select 1] call ars_inf_tent;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 0, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];

//Delta
_caja addAction ["Loadout <t color='#00BB2D'>TENIENTE</t>", {[_this select 1] call ars_delta_Tent;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>CABO</t>", {[_this select 1] call ars_delta_Cabo;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>MEDICO</t>", {[_this select 1] call ars_delta_Medic;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>INGENIERO</t>", {[_this select 1] call ars_delta_Ing;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>TD</t>", {[_this select 1] call ars_delta_TD;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>MG</t>", {[_this select 1] call ars_delta_MG;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>AT</t>", {[_this select 1] call ars_delta_AT;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#00BB2D'>SOLDADO</t>", {[_this select 1] call ars_delta_sold;(_this select 1) setUnitTrait ["Medic",true];(_this select 1) setVariable["ACE_medical_medicClass", 1, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && (_this getVariable ["esDelta", false]) && !(_this getVariable ["esApoyo", false])'];

//Apoyo
_caja addAction ["Loadout <t color='#004EBB'>PILOTO</t>", {[_this select 1] call ars_apy_piloto;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && (_this getVariable ["esApoyo", false])'];
_caja addAction ["Loadout <t color='#004EBB'>TANQUISTA</t>", {[_this select 1] call ars_apy_tanquista;(_this select 1) setUnitTrait ["Medic",false];(_this select 1) setVariable["ACE_medical_medicClass", 0, true];(_this select 1) setVariable["ACE_isEngineer", 1, true];}, nil,1,false,true,'', '_this distance _target < 5 && !(_this getVariable ["esDelta", false]) && (_this getVariable ["esApoyo", false])'];
